[package]
name = "map-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
image = "0.25.2"
rand = "0.8.5"
smog = {path = "../smog"}
solver = {path = "../solver"}
text_io = "0.1.12"
