[package]
name = "packet-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
tokio = { version = "1.39.2", features = ["full"] }
serde = { version = "1.0.*", default-features = false }
postcard = { version = "1.0.0", features = ["use-std"] }
