[package]
name = "smog"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
bytemuck = "1.16.1"
rand = "0.8.5"
rayon = "1.10.0"
wgpu = "0.20.1"
tokio = { version = "1.39.2", features = ["full"] }
crossbeam-channel = "0.5.13"
packet-tools = {path = "../packet-tools"}
server = {path = "../server"}

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
